// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proto/v1/simple/models.proto

package models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Simple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Simple) Reset() {
	*x = Simple{}
	mi := &file_proto_v1_simple_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple) ProtoMessage() {}

func (x *Simple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simple_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple.ProtoReflect.Descriptor instead.
func (*Simple) Descriptor() ([]byte, []int) {
	return file_proto_v1_simple_models_proto_rawDescGZIP(), []int{0}
}

func (x *Simple) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Simple) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" validate:"required,gt=0"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" validate:"required,min=1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDTO) Reset() {
	*x = CreateDTO{}
	mi := &file_proto_v1_simple_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDTO) ProtoMessage() {}

func (x *CreateDTO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simple_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDTO.ProtoReflect.Descriptor instead.
func (*CreateDTO) Descriptor() ([]byte, []int) {
	return file_proto_v1_simple_models_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDTO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_v1_simple_models_proto protoreflect.FileDescriptor

const file_proto_v1_simple_models_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/simple/models.proto\x12\x04user\x1a)github.com/alta/protopatch/patch/go.proto\"[\n" +
	"\x06Simple\x12 \n" +
	"\x02id\x18\x01 \x01(\x03B\x10ʵ\x03\f\xa2\x01\tjson:\"id\"R\x02id\x12/\n" +
	"\amessage\x18\x02 \x01(\tB\x15ʵ\x03\x11\xa2\x01\x0ejson:\"message\"R\amessage\"\x91\x01\n" +
	"\tCreateDTO\x129\n" +
	"\x02id\x18\x01 \x01(\x03B)ʵ\x03%\xa2\x01\"json:\"id\" validate:\"required,gt=0\"R\x02id\x12I\n" +
	"\amessage\x18\x02 \x01(\tB/ʵ\x03+\xa2\x01(json:\"message\" validate:\"required,min=1\"R\amessageB9Z7github.com/go-jedi/go-kafka-test/proto/v1/simple/modelsb\x06proto3"

var (
	file_proto_v1_simple_models_proto_rawDescOnce sync.Once
	file_proto_v1_simple_models_proto_rawDescData []byte
)

func file_proto_v1_simple_models_proto_rawDescGZIP() []byte {
	file_proto_v1_simple_models_proto_rawDescOnce.Do(func() {
		file_proto_v1_simple_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_simple_models_proto_rawDesc), len(file_proto_v1_simple_models_proto_rawDesc)))
	})
	return file_proto_v1_simple_models_proto_rawDescData
}

var file_proto_v1_simple_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_simple_models_proto_goTypes = []any{
	(*Simple)(nil),    // 0: user.Simple
	(*CreateDTO)(nil), // 1: user.CreateDTO
}
var file_proto_v1_simple_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_simple_models_proto_init() }
func file_proto_v1_simple_models_proto_init() {
	if File_proto_v1_simple_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_simple_models_proto_rawDesc), len(file_proto_v1_simple_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_simple_models_proto_goTypes,
		DependencyIndexes: file_proto_v1_simple_models_proto_depIdxs,
		MessageInfos:      file_proto_v1_simple_models_proto_msgTypes,
	}.Build()
	File_proto_v1_simple_models_proto = out.File
	file_proto_v1_simple_models_proto_goTypes = nil
	file_proto_v1_simple_models_proto_depIdxs = nil
}
