// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proto/v1/simple/simple.proto

package models

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_v1_simple_simple_proto protoreflect.FileDescriptor

const file_proto_v1_simple_simple_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/simple/simple.proto\x12\x04user\x1a)github.com/alta/protopatch/patch/go.proto\x1a\x1cproto/v1/simple/models.proto28\n" +
	"\rSimpleService\x12'\n" +
	"\x06Create\x12\x0f.user.CreateDTO\x1a\f.user.SimpleB9Z7github.com/go-jedi/go-kafka-test/proto/v1/simple/modelsb\x06proto3"

var file_proto_v1_simple_simple_proto_goTypes = []any{
	(*CreateDTO)(nil), // 0: user.CreateDTO
	(*Simple)(nil),    // 1: user.Simple
}
var file_proto_v1_simple_simple_proto_depIdxs = []int32{
	0, // 0: user.SimpleService.Create:input_type -> user.CreateDTO
	1, // 1: user.SimpleService.Create:output_type -> user.Simple
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_simple_simple_proto_init() }
func file_proto_v1_simple_simple_proto_init() {
	if File_proto_v1_simple_simple_proto != nil {
		return
	}
	file_proto_v1_simple_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_simple_simple_proto_rawDesc), len(file_proto_v1_simple_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_simple_simple_proto_goTypes,
		DependencyIndexes: file_proto_v1_simple_simple_proto_depIdxs,
	}.Build()
	File_proto_v1_simple_simple_proto = out.File
	file_proto_v1_simple_simple_proto_goTypes = nil
	file_proto_v1_simple_simple_proto_depIdxs = nil
}
